version: 2

# Currently being used for local builds only
# To build run:
#   goreleaser release --snapshot --clean

project_name: npm-malicious-package-check

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.xz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

#changelog:
#  sort: asc
#  filters:
#    exclude:
#      - "^docs:"
#      - "^test:"

#signs:
#  - cmd: cosign
#    signature: "${artifact}.sig"
#    certificate: "${artifact}.pem"
#    artifacts: all
#    output: true
#    args:
#      - sign-blob
#      - '--oidc-provider=github-actions'
#      - '--output-certificate=${certificate}'
#      - '--output-signature=${signature}'
#      - '${artifact}'
#      - --yes
